### ISSUE TITLE
DFD Comments October 4

### ISSUE THREAD

**Issue by germonprez** [dgrace022/assignment1-3420#11]
Hi Matt, 

A few comments: 

1) This dataflow can be removed. 

<img width="198" alt="screen shot 2016-10-04 at 5 41 56 pm" src="https://cloud.githubusercontent.com/assets/656208/19095168/ec5a860c-8a59-11e6-9d61-ee228f10f252.png">

2) The developer needs to connect to this process (similar to the Manager). This is how the Developer can get Software Project Information 

<img width="232" alt="screen shot 2016-10-04 at 7 42 42 pm" src="https://cloud.githubusercontent.com/assets/656208/19097502/dfb53a6c-8a6a-11e6-9e2f-e278b3adca4c.png">

3) With respect to point 2 above, the request and response should be for Software Project License and Vulnerability Information (Not package). 

4) Regarding Policy, the dataflows called OSS Project Request and OSS Project Response are not the best names here. These dataflows should really just be about requesting policy information. 

This is a good start and I hope these comments help. 

MG

**Comment by dgrace022** [comment]
I made the corrections.
