### ISSUE TITLE
DFD Comments October 5

### ISSUE THREAD

**Issue by germonprez** [dgrace022/assignment1-3420#14]
Overall, the structure is good. The only thing that I'm seeing right now is in this image: 

<img width="257" alt="screen shot 2016-10-05 at 5 41 52 am" src="https://cloud.githubusercontent.com/assets/656208/19110258/97f78276-8abe-11e6-8d38-aa54d71d6565.png">

Those dataflows should be named Software Project License and Vulnerability Request (and Response). These need to be parallel with the dataflows that precede them. 

MG

**Comment by dgrace022** [comment]
Done!
